services:
  db:
    image: postgres
    restart: always
    secrets:
      - db-password
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./init:/docker-entrypoint-initdb.d
    networks:
      - spring-postgres
    environment:
      - POSTGRES_DB=car-metrics
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD_FILE=/run/secrets/db-password
    ports:
      - "5432:5432"
volumes:
  db-data:
secrets:
  db-password:
    file: db-password-postgres
networks:
  spring-postgres: